#!/bin/sh

# Run all scripts defined in the commit-msg-hooks directory.
# This allows individual operations/verifications/restriction to be stored in their own files.
set -e
basedir=$(dirname "$0")
for f in "$basedir"/commit-msg-hooks/*.sh; do
  sh "$f" "$1"
done
