#!/bin/sh

# Run all scripts defined in the pre-commit-hooks directory.
# This allows individual operations/verifications/restriction to be stored in their own files.
set -e
basedir=$(dirname "$0")
for f in "$basedir"/pre-commit-hooks/*.sh; do
  sh "$f"
done
