language: sh

script:
  - set -ex; [ "$BUILD" = "osx" ] && sudo port install shellcheck; set +x;
  - make

matrix:
  include:
    - os: linux
      env: BUILD=linux
    - os: osx
      env: BUILD=osx
