language: sh

script:
  - set -ex; [ "$BUILD" = "osx" ] && wget -qO- "https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.darwin.x86_64.tar.xz" | tar -xJv && alias shellcheck="$(pwd)/shellcheck-stable/shellcheck" && alias xargs='xargs '; set +x;
  - make

matrix:
  include:
    - os: linux
      env: BUILD=linux
    - os: osx
      env: BUILD=osx
